### ISSUE TITLE
symbol `_EMBED_INFO_PLIST` is already defined

### ISSUE THREAD

**Issue by aneesijaz** [nvzqz/embed-plist-rs#2] opened 2022-01-15 18:40 UTC
**Type**: `Bug`
Getting error on making a call to 
```rust
embed_plist::embed_info_plist!("../Info.plist");
```
Here's a screenshot let me know if I am doing something wrong.
I am actually new to rust and still learning and finding my way around let me if I am missing something.

<img width="1107" alt="Screenshot 2022-01-15 at 11 34 50 PM" src="https://user-images.githubusercontent.com/23694746/149633933-48bd80fc-1cb4-4e76-85b3-e15a78c29f0c.png">

**Rust Version**:  `1.57.0`
**Tauri**: `{ version = "1.0.0-beta.8", features = ["api-all"] }`
**OS**: `Mac Os Big Sur (11.6.1)`
**embed-plist**: `1.2.0`

**Comment by nvzqz** [comment] 2022-01-16 18:49
It appears that [Tauri embeds your `Info.plist` for you in `dev` builds](https://github.com/tauri-apps/tauri/pull/2444).

Because of how this crate is implemented, you cannot override Tauri's invocation of `embed_info_plist!`. Having a compile error on `_EMBED_INFO_PLIST` is a feature to catch this issue. Because this is expected behavior, I'm going to close this issue.

**Closed as completed by nvzqz** 2022-01-16 18:49 UTC
